### ISSUE TITLE
fish: Unknown command 'npm' when using .fnmrc

### ISSUE THREAD

**Issue by deanmarano** [jorgebucaran/fnm#64]
#42 Hi! I've been using fish for about a year, and your package is a life saver! Thanks so much 🙏 I'm seeing an issue where a .fnmrc (or .nvmrc, .node-version) breaks my npm. Interestingly, the node executable works.

```shell
$ npm i
fish: Unknown command 'npm'
~/.config/fish/functions/__fnm_run_bin_as.fish (line 52):
        command npm $argv
                ^
in function '__fnm_run_bin_as'
        called on line 2 of file ~/.config/fish/functions/./npm.fish
        with parameter list 'npm i'

in function 'npm'
        called on standard input
        with parameter list 'i'
$ node -v
v8.10.0
$ which node
 #/Users/dean/.config/fnm/bin/node
$ which npm
$
$ tree ~/.config/fnm
/Users/qxr9638/.config/fnm
├── bin
│   ├── node
│   ├── npm -> ../lib/node_modules/npm/bin/npm-cli.js
│   └── npx -> ../lib/node_modules/npm/bin/npx-cli.js
├── etc
└── versions
    └── 8.9.4

3 directories, 4 files
```

If I install using the fnm command, it works fine. It looks like my install is having some confusing between the config and cache dir.

What could I provide to make this easier to debug?

**Comment by deanmarano** [comment]
Nope, I stopped using fnm for these projects.

**Comment by TakuyaAbe** [comment]
I'm having exactly the same issue.
I don't remember when the issue occurs...

I managed to escape the state by uninstalling the fnm, remove fnm's directory & reinstall fnm.

```sh
$ npm -v
fish: Unknown command 'npm'
~/.config/fish/functions/__fnm_run_bin_as.fish (line 52):
        command npm $argv
                ^
in function '__fnm_run_bin_as'
        called on line 2 of file ~/.config/fish/functions/npm.fish
        with parameter list 'npm'

in function 'npm'
        called on standard input
$ fisher uninstall fnm
$ cd /Users/(myUserName)/.config/ 
$ rm -rf fnm
$ fisher fnm
$ fnm latest
$ npm -v
6.4.1
```

Environmental Info
```
Mac OS High Sierra 10.13.6
fisherman version 2.13.2 ~/.config/fish/functions/fisher.fish
fnm v1.8.3
```

**Comment by fibric** [comment]
I have the same issue since I set up everything from scratch because I got a new MBP.
- `macOS Mojave 10.14 (18A391)`
- `fish, version 2.7.1`
    - installed via `brew install fish`
- `fisher version 3.1.1 ~/.config/fish/functions/fisher.fish`
    - installed via `curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish`
- `fnm v1.8.3`
    - installed `fisher add fisherman/fnm`
```shell
$ fnm ls
  ...
  8.10.0
  ...
  • 11.0.0
```
On my Mac Pro with the same versions in place, I don't have this issue.

**Comment by deanmarano** [comment]
I've switched to using https://github.com/asdf-vm/asdf for a global version manager.
